### ISSUE TITLE
Submit button un-clickable on mobile

### ISSUE THREAD

**Issue by CodedAnkit** [CodedAnkit/BMI-Calculator#1]
Submit button is un-clickable on mobile devices.

**Comment by summerkoushal** [comment]
i want to work on this issue.

**Comment by CodedAnkit** [comment]
> i want to work on this issue.

Feel free to make any additions 😀

**Comment by summerkoushal** [comment]
assign this issue to me plz

**Comment by CodedAnkit** [comment]
> assign this issue to me plz

@summerkoushal Done.

**Comment by CodedAnkit** [comment]
Resolved
